# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy Resources

on:
  push:
    branches:
        - main

permissions:
    id-token: write
    actions: read
    contents: read

jobs: