# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Generate Bicep Snapshot

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  BICEP_TEMPLATE: main.bicep
  BICEP_PARAMETERS: main.bicepparam
  LOCATION: uksouth

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment
        uses: actions/github-script@v8
        with:
          script: |
            const marker = "<!-- bicep-snapshot-comment -->";
            const body = `${marker}
            Bicep snapshot workflow triggered for this PR.
            I will now validate the Bicep snapshot.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

  validate-snapshot:
    name: Validate snapshot
    runs-on: ubuntu-latest
    needs: comment-on-pr
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout PR head commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check for Bicep Snapshot
        id: check-snapshot
        shell: pwsh
        run: |
          if (Test-Path -Path "main.snapshot.json") {
              Write-Host "Bicep snapshot file found."
              echo "snapshot_exists=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
              Write-Host "No Bicep snapshot file found. Please ensure that the snapshot file is present in the PR for validation."
              echo "snapshot_exists=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Comment no snapshot found
        if: steps.check-snapshot.outputs.snapshot_exists == 'false'
        uses: actions/github-script@v8
        with:
          script: |
            const marker = "<!-- bicep-snapshot-exists-result -->";
            const body = `${marker}
            No Bicep snapshot file found. Please ensure that the snapshot file is present in the PR for validation.
            This job will now fail as the snapshot file is required for validation.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: fail job if no snapshot found
        if: steps.check-snapshot.outputs.snapshot_exists == 'false'
        shell: pwsh
        run: |
          Write-Host "Failing the job as no snapshot file was found for validation."
          exit 1

      - name: Setup Bicep CLI
        uses: anthony-c-martin/setup-bicep@v0.3

      - name: Validate snapshot
        id: validate-snapshot
        continue-on-error: true
        shell: pwsh
        run: |
          $snapshot_result = bicep snapshot main.bicepparam --mode validate --subscription-id ${{ secrets.AZURE_SUBSCRIPTION_ID }} --location uksouth

          if ($snapshot_result -eq $null) {
              Write-Host "No resource changes detected in the snapshot."
              $snapshot_result = "No resource changes in the Bicep deployment were detected in the snapshot."
          } else {
              Write-Host "Resource changes detected in the snapshot: Please review the results."
              $snapshot_result = "Resource changes detected in the Bicep deployment: Please review the results in the Validate snapshot step."

              Write-Host "-------------- Review resource changes --------------"
              bicep snapshot main.bicepparam --mode validate --subscription-id ${{ secrets.AZURE_SUBSCRIPTION_ID }} --location uksouth
              Write-Host "-----------------------------------------------------"
          }
          "snap_shot_result=$snapshot_result" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Comment Results on PR
        uses: actions/github-script@v8
        with:
          script: |
            const marker = "<!-- bicep-snapshot-result -->";
            const body = `${marker}
            Snapshot validation completed: ${{ steps.validate-snapshot.outputs.snap_shot_result }}
            
            Click the following link to see the run result: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
